project:
  type: website
  output-dir: docs # very important for getting the website to display properly when you use GitHub Pages

website:
  title: "A Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - addition.qmd
      - multiplication.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
